services:
  creolytixecommerce.api:
    image: ${DOCKER_REGISTRY-}creolytixecommerceapi
    build:
      context: .
      dockerfile: CreolytixECommerce.API/Dockerfile
    ports:
      - "5002:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - RabbitMqSettings__HostName=rabbitmq
      - RabbitMqSettings__UserName=guest
      - RabbitMqSettings__Password=guest
      - MongoDbSettings__ConnectionString=mongodb://mongo:27017
      - MongoDbSettings__DatabaseName=CreolytixECommerce
    depends_on:
      rabbitmq:
        condition: service_healthy
      mongo:
        condition: service_started

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=CreolytixECommerce

networks:
  default:
    driver: bridge

volumes:
  mongo_data:
